version: "3"
services:
  url_location:
    image:  baicailin/url_location
    restart: always
    depends_on:
      - headless_shell
    # build: ./..
    command: /app/url_location -c=/app/conf/config.yaml
    volumes:
      - ./conf:/app/conf
      - ./autocert:/app/autocert
      - ./log:/app/log
      # - ./upload:/app/upload
      # - /tmp:/app/upload
    environment:
      CHROMEDP_REMOTE_DEBUG_URL: ws://headless_shell:9222
      TZ: Asia/Shanghai
    ports:
      - "8081:8080"

  headless_shell:
    image:  chromedp/headless-shell
    restart: always
    # build: ./..
    # command: /app/pbbot_app_huizhuanfa -c=/app/conf/config.yaml
    # volumes:
    #   - ./conf:/app/conf
    #   - ./autocert:/app/autocert
    #   - ./log:/app/log
    #   - ./upload:/app/upload
      # - /tmp:/app/upload
    # environment:
    #   TZ: Asia/Shanghai
    ports:
      - "9222:9222"