# 服务绑定端口
addr: :8080
# 服务器的ip:port
url: http://127.0.0.1:8080
# 自检服务重试的次数
max_ping_count: 10
#TLS服务域名(可选配置)
autotls_domain:  api.lyhuilin.com
#打开Tls配置，true开启TLS服务，false会关闭TLS服务。 (可选配置)
autotls_enable:  false
# tls证书key文件路径
tls_key_file: "./cert/apiclient.key"
# tls证书pem文件路径
tls_pem_file: "./cert/apiclient.pem"
#
## openapi的日志相关配置说明。
# writers: 输出位置，有2个可选项：file,stdout。选择file会将日志记录到logger_file指定的日志文件中，选择stdout会将日志输出到标准输出，当然也可以两者同时选择
# logger_level: 日志级别，DEBUG, INFO, WARN, ERROR, FATAL
# logger_file: 日志文件
# log_format_text: 日志的输出格式，json或者plaintext，true会输出成json格式，false会输出成非json格式
# rollingPolicy: rotate依据，可选的有：daily, size。如果选daily则根据天进行转存，如果是size则根据大小进行转存
# log_rotate_date: rotate转存时间，配合rollingPolicy: daily使用
# log_rotate_size: rotate转存大小，配合rollingPolicy: size使用
# log_backup_count:当日志文件达到转存标准时，log系统会将该日志文件进行压缩备份，这里指定了备份文件的最大个数。
# openapi的日志相关配置。
log:
  writers: file,stdout
  logger_level: INFO
  logger_file: log/url_location.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
#
# chromedp远程调试地址 ws://127.0.0.1:9222
chromedp_remote_debug_url: ""
# chromedp远程调试端口 9222
chromedp_remote_debug_port: ""
# 支持跳转的域名列表 https://www.zzzdm.com/go|https://go.smzdm.com
chromedp_can_wait_domain_list: ""